name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  custom_themer_annotations:
    path: ../../custom_themer_annotations/
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  custom_themer:
    path: ../../custom_themer/
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
